spring:
  application:
    name: chat-task

  datasource:
    url: jdbc:postgresql://localhost:5432/capstone_chat_task
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      password: 123456
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 42246574521-f8gnomb39ndhkl5g2u21fn6ig6konvq1.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/api/v1/auth/google/callback

  rabbitmq:
    listener:
      id: chat-listener
    login:
      queue: login_queue
      exchange: login_exchange
      routing-key: login_routing_key
    notification:
      queue: notification_queue
      exchange: notification_exchange
      routing-key: notification_routing_key
      delete-queue: notification_delete_queue
      delete-exchange: notification_delete_exchange
      delete-routing-key: notification_delete_routing_key
    conversations:
      members:
        add-queue: conversation_add_member_queue
        add-exchange: conversation_add_member_exchange
        add-routing-key: conversation_add_member_routing_key
        delete-queue: conversation_delete_member_queue
        delete-exchange: conversation_delete_member_exchange
        delete-routing-key: conversation_delete_member_routing_key

  mail:
    host: smtp.gmail.com
    port: 587
    username: thuyphuocthinhtpt1@gmail.com
    password: vtwy iuhb hgkh djia
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

jwt:
  secret: qQ5xB!93@kVZ&nL#7fJe$uPwRz8XtA2mDgYsTc0^HlEoMb9CUiKgN1s6WdFYrp3x
  accessTokenExpiration: 900000
  refreshTokenExpiration: 259200000

cloudinary:
  cloud-name: dy0m9udjz
  api-key: 655763378773479
  api-secret: 7CheewENHiovwVJtdW4ZJLBNoW8

logging:
  level:
    org:
      springframework:
        security: DEBUG
        orm:
          jpa: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE





