module chat.task {
    requires cloudinary.core;
    requires com.fasterxml.jackson.databind;
    requires com.google.api.client;
    requires com.google.auth.oauth2;
    requires com.nimbusds.jose.jwt;
    requires jakarta.transaction;
    requires jakarta.validation;
    requires jjwt.api;
    requires static lombok;
    requires org.apache.tomcat.embed.core;
    requires org.hibernate.orm.core;
    requires redis.clients.jedis;
    requires spring.amqp;
    requires spring.beans;
    requires spring.boot;
    requires spring.boot.autoconfigure;
    requires spring.context;
    requires spring.context.support;
    requires spring.core;
    requires spring.data.commons;
    requires spring.data.jpa;
    requires spring.messaging;
    requires spring.rabbit;
    requires spring.security.config;
    requires spring.security.core;
    requires spring.security.crypto;
    requires spring.security.messaging;
    requires spring.security.web;
    requires spring.tx;
    requires spring.web;
    requires spring.websocket;
    requires jakarta.persistence;
}